[project]
name = "notion-notification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
]

[dependency-groups]
lint = [
    "ruff>=0.11.8",
]
